// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqcfmgrljogvfadbjuao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxY2ZtZ3Jsam9ndmZhZGJqdWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTQ4MTcsImV4cCI6MjA2OTEzMDgxN30.E25JX89fLx5Ys4wv5sM_DHOsWfrxYoCJfzigHcwQN_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});